/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-18 00:29:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_005fchoice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html >\n");
      out.write("\t<head>\n");
      out.write("\t\t<meta charset=\"utf-8\">\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("\t\t<title>다님: 선택하기</title>\n");
      out.write("\n");
      out.write("\t\t<!-- Google font -->\n");
      out.write("\t\t<link href=\"https://fonts.googleapis.com/css?family=Lato:700%7CMontserrat:400,600\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("\t\t<!-- Bootstrap -->\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"/danim/resources/css/bootstrap.min.css\"/>\n");
      out.write("\n");
      out.write("\t\t<!-- Font Awesome Icon -->\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/danim/resources/css/font-awesome.min.css\">\n");
      out.write("\n");
      out.write("\t\t<!-- Custom stlylesheet -->\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"/danim/resources/css/style.css\"/>\n");
      out.write("\t\t\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-1.12.4.min.js\" ></script>\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("\t<body>\n");
      out.write("\n");
      out.write("\t\t<!-- Header -->\n");
      out.write("\t\t<header id=\"header\">\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t\t<!-- Logo -->\n");
      out.write("\t\t\t\t\t<div class=\"navbar-brand\">\n");
      out.write("\t\t\t\t\t\t<a class=\"logo\" href=\"index.do\">\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/danim/resources/img/logo.png\" alt=\"logo\">\n");
      out.write("\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- /Logo -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- Mobile toggle -->\n");
      out.write("\t\t\t\t\t<button class=\"navbar-toggle\">\n");
      out.write("\t\t\t\t\t\t<span></span>\n");
      out.write("\t\t\t\t\t</button>\n");
      out.write("\t\t\t\t\t<!-- /Mobile toggle -->\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- Navigation -->\n");
      out.write("\t\t\t\t<nav id=\"nav\">\n");
      out.write("\t\t\t\t\t<ul class=\"main-menu nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.do\">메인으로</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"loginForm.do\">로그인</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"enrollForm.do\">회원가입</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"contactForm.do\">문의하기</a></li>\n");
      out.write("\t\t\t\t\t\t<li><a href=\"noticeForm.do\">공지사항</a></li>\n");
      out.write("\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t</nav>\n");
      out.write("\t\t\t\t<!-- /Navigation -->\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</header>\n");
      out.write("\t\t<!-- /Header -->\n");
      out.write("\n");
      out.write("\t\t<!-- Hero-area -->\n");
      out.write("\t\t<div class=\"hero-area section\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- Backgound Image -->\n");
      out.write("\t\t\t<div class=\"bg-image bg-parallax overlay\" style=\"background-image:url(/danim/resources/img/page-background.jpg)\"></div>\n");
      out.write("\t\t\t<!-- /Backgound Image -->\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"col-md-10 col-md-offset-1 text-center\">\n");
      out.write("\t\t\t\t\t\t<ul class=\"hero-area-tree\">\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.do\">Danim:</a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t\t<h1 class=\"white-text\">선택하기</h1>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- /Hero-area -->\n");
      out.write("\n");
      out.write("\t\t<!-- Contact -->\n");
      out.write("\t\t<div id=\"contact\" class=\"section\" >\n");
      out.write("\n");
      out.write("\t\t\t<!-- container -->\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- row -->\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- login form -->\n");
      out.write("\t\t\t\t\t<br><br>\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5 col-md-offset-4\">\n");
      out.write("\t\t\t\t\t\t<div class=\"contact-form\">\n");
      out.write("\t\t\t\t\t\t\t<h4>Choice</h4>\n");
      out.write("\t\t\t\t\t\t\t<a class=\"main-button icon-button\" href=\"#\" style=\"width: 100%;\">다님이에게 도움받기</a> <br><br>\n");
      out.write("\t\t\t\t\t\t\t<a class=\"main-button icon-button\" href=\"#\" style=\"width: 100%;\">도움주기</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- /login form -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- /row -->\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- /container -->\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<!-- /Contact -->\n");
      out.write("\n");
      out.write("\t\t<!-- Footer -->\n");
      out.write("\t\t<footer id=\"footer\" class=\"section\">\n");
      out.write("\n");
      out.write("\t\t\t<!-- container -->\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- row -->\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- footer logo -->\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-logo\">\n");
      out.write("\t\t\t\t\t\t\t<a class=\"logo\" href=\"index.do\">\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/danim/resources/img/logo.png\" alt=\"logo\">\n");
      out.write("\t\t\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- /row -->\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- row -->\n");
      out.write("\t\t\t\t<div id=\"bottom-footer\" class=\"row\">\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- social -->\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 col-md-push-8\">\n");
      out.write("\t\t\t\t\t\t<ul class=\"footer-social\">\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"instagram\"><i class=\"fa fa-instagram\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"github\"><i class=\"fa fa-github\"></i></a></li>\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- /social -->\n");
      out.write("\n");
      out.write("\t\t\t\t\t<!-- copyright -->\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-md-pull-4\">\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-copyright\">\n");
      out.write("\t\t\t\t\t\t\t<span>&copy; Copyright Koo gun mo. | This Poroject is made with Kim nam gyu & You young joon</a></span>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<!-- /copyright -->\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- row -->\n");
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- /container -->\n");
      out.write("\n");
      out.write("\t\t</footer>\n");
      out.write("\t\t<!-- /Footer -->\n");
      out.write("\n");
      out.write("\t\t<!-- preloader -->\n");
      out.write("\t\t<div id='preloader'><div class='preloader'></div></div>\n");
      out.write("\t\t<!-- /preloader -->\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t<!-- jQuery Plugins -->\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/danim/resources/js/jquery.min.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/danim/resources/js/bootstrap.min.js\"></script>\n");
      out.write("\t\t<script src=\"https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/danim/resources/js/google-map.js\"></script>\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/danim/resources/js/main.js\"></script>\n");
      out.write("\n");
      out.write("\t</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
