/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-23 04:02:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class enroll_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\t <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("\r\n");
      out.write("\t\t<title>다님: 회원가입</title>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Google font -->\r\n");
      out.write("\t\t<link href=\"https://fonts.googleapis.com/css?family=Lato:700%7CMontserrat:400,600\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Bootstrap -->\r\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"/danim/resources/css/bootstrap.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Font Awesome Icon -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/danim/resources/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Custom stlylesheet -->\r\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"/danim/resources/css/style.css\"/>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-1.12.4.min.js\" ></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<head>\r\n");
      out.write("\t\t\t<title>Enroll</title>\r\n");
      out.write("\t\t\t<meta charset=\"utf-8\" />\r\n");
      out.write("\t\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, user-scalable=no\" />\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"../resources/css/enroll.css\" />\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"/Sector/resources/css/searchform.css\" />\r\n");
      out.write("\t\t\t<link id=\"dark-mode-sheet\"\r\n");
      out.write("\t\t\t\t\trel=\"stylesheet\"\r\n");
      out.write("\t\t\t\t\thref=\"../resources/css/darkmode.css\"\r\n");
      out.write("\t\t\t\t\tmedia=\"(prefers-color-scheme: dark)\">\r\n");
      out.write("\t\t\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/js-cookie/2.2.1/js.cookie.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"../resources/js/darkmode.js\"></script>\r\n");
      out.write("\t\t\t<script type=\"text/javascript\" src=\"../resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t\t<noscript><link rel=\"stylesheet\" href=\"../resources/css/noscript.css\" /></noscript>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t var checkcnt = 0;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t var getMail = RegExp(/^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/);\r\n");
      out.write("\t\t\t var getCheck= RegExp(/^[a-zA-Z0-9]{4,12}$/);\r\n");
      out.write("\t\t\t var getPwd = RegExp(/^(?=.*[a-zA-Z])((?=.*\\d)|(?=.*\\W)).{6,12}$/);\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t var fmt = RegExp(/^\\d{6}[1234]\\d{6}$/); //형식 설정\r\n");
      out.write("\t\t\t//  var buf = new Array(13); //주민등록번호 배열\r\n");
      out.write("\t\t\t\tfunction validate() {\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\t  //아이디 공백 확인\r\n");
      out.write("\t\t\t\t\t  if($(\"#userid\").val() == \"\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#userid\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t //이메일 공백 확인\r\n");
      out.write("\t\t\t\t\t  if($(\"#email\").val() == \"\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"이메일을 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#email\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  if($(\"#userpwd\").val() == \"\" || $(\"#userpwd2\").val() == \"\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"비밀번호를 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#userpwd\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#userpwd2\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#userpwd\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t  if($(\"#username\").val() == \"\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"이름을 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#username\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t  if($(\"#phone\").val() == \"\"){\r\n");
      out.write("\t\t\t\t\t\talert(\"전화번호를 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#phone\").focus();\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t  //주민번호\r\n");
      out.write("\t\t\t\t\t  if(($(\"#usernumber1\").val() == \"\") || ($(\"#usernumber2\").val() == \"\")){\r\n");
      out.write("\t\t\t\t\t    alert(\"주민등록번호를 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\t    $(\"#usernumber1\").focus();\r\n");
      out.write("\t\t\t\t\t    return false;\r\n");
      out.write("\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\t  if(check_jumin() == false){\r\n");
      out.write("\t\t\t\t\t    return false;\r\n");
      out.write("\t\t\t\t\t  } \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tif($(\"#agree\").prop(\"checked\") != true){\r\n");
      out.write("\t\t\t\t\t\talert(\"이용 약관에 동의해주세요.\");\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t\talert(\"회원이 되신걸 축하드립니다!\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t\t// return true;\r\n");
      out.write("\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t//   //주민번호 확인 함수\r\n");
      out.write("\t\t\t\t//   function check_jumin() {\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t//     var jumins3 = $(\"#usernumber1\").val() + $(\"#usernumber2\").val();\r\n");
      out.write("\t\t\t\t//       //주민등록번호 생년월일 전달\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t//       var fmt = RegExp(/^\\d{6}[1234]\\d{6}$/)  //포멧 설정\r\n");
      out.write("\t\t\t\t//       var buf = new Array(13);\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t//       //주민번호 유효성 검사\r\n");
      out.write("\t\t\t\t//       if (!fmt.test(jumins3)) {\r\n");
      out.write("\t\t\t\t//         alert(\"주민등록번호 형식에 맞게 입력해주세요.\");\r\n");
      out.write("\t\t\t\t//         $(\"#usernumber1\").focus();\r\n");
      out.write("\t\t\t\t//         return false;\r\n");
      out.write("\t\t\t\t//       }\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t//       //주민번호 존재 검사\r\n");
      out.write("\t\t\t\t//       for (var i = 0; i < buf.length; i++){\r\n");
      out.write("\t\t\t\t//         buf[i] = parseInt(jumins3.charAt(i));\r\n");
      out.write("\t\t\t\t//       }\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t//       var multipliers = [2,3,4,5,6,7,8,9,2,3,4,5];// 밑에 더해주는 12자리 숫자들 \r\n");
      out.write("\t\t\t\t//       var sum = 0;\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t//       for (var i = 0; i < 12; i++){\r\n");
      out.write("\t\t\t\t//       sum += (buf[i] *= multipliers[i]);// 배열끼리12번 돌면서 \r\n");
      out.write("\t\t\t\t//     }\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t//     if ((11 - (sum % 11)) % 10 != buf[12]) {\r\n");
      out.write("\t\t\t\t//       alert(\"잘못된 주민등록번호 입니다.\");\r\n");
      out.write("\t\t\t\t//       $(\"#usernumber1\").focus();\r\n");
      out.write("\t\t\t\t//       return false;\r\n");
      out.write("\t\t\t\t//     }\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t//   } \r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t//   function juminCheck(){\r\n");
      out.write("\t\t\t\t// \tdocument.getElementById(\"usernumber1\").style.borderBottom=\"solid 1px #c9c9c9\";\r\n");
      out.write("\t\t\t\t// \tdocument.getElementById(\"usernumber2\").style.borderBottom=\"solid 1px #c9c9c9\";\r\n");
      out.write("\t\t\t\t// \tvar jumins3 = $(\"#usernumber1\").val() + $(\"#usernumber2\").val();\r\n");
      out.write("\t\t\t\t//       //주민등록번호 생년월일 전달\r\n");
      out.write("\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t//       var fmt = RegExp(/^\\d{6}[1234]\\d{6}$/)  //포멧 설정\r\n");
      out.write("\t\t\t\t//       var buf = new Array(13);\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t//       //주민번호 유효성 검사\r\n");
      out.write("\t\t\t\t//       if (!fmt.test(jumins3)) {\r\n");
      out.write("\t\t\t\t//         alert(\"주민등록번호 형식에 맞게 입력해주세요.\");\r\n");
      out.write("\t\t\t\t//         $(\"#usernumber1\").focus();\r\n");
      out.write("\t\t\t\t//         return false;\r\n");
      out.write("\t\t\t\t//       }\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t//       //주민번호 존재 검사\r\n");
      out.write("\t\t\t\t//       for (var i = 0; i < buf.length; i++){\r\n");
      out.write("\t\t\t\t//         buf[i] = parseInt(jumins3.charAt(i));\r\n");
      out.write("\t\t\t\t//       }\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t//       var multipliers = [2,3,4,5,6,7,8,9,2,3,4,5];// 밑에 더해주는 12자리 숫자들 \r\n");
      out.write("\t\t\t\t//       var sum = 0;\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t//       for (var i = 0; i < 12; i++){\r\n");
      out.write("\t\t\t\t//       sum += (buf[i] *= multipliers[i]);// 배열끼리12번 돌면서 \r\n");
      out.write("\t\t\t\t//     }\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t//     if ((11 - (sum % 11)) % 10 != buf[12] && $(\"#usernumber1\").val() != \"\" && $(\"#usernumber2\").val() != \"\") {\r\n");
      out.write("\t\t\t\t//       alert(\"잘못된 주민등록번호 입니다.\");\r\n");
      out.write("\t\t\t\t// \t  $(\"#usernumber1\").focus();\r\n");
      out.write("\t\t\t\t// \t  $(\"#usernumber2\").val(\"\");\r\n");
      out.write("\t\t\t\t// \t  return false;\r\n");
      out.write("\t\t\t\t// \t}\r\n");
      out.write("\t\t\t\t// \t  var userno =  $(\"#usernumber1\").val() + \"-\" + $(\"#usernumber2\").val();\r\n");
      out.write("\t\t\t\t// \t    $.ajax({\r\n");
      out.write("\t\t\t\t//             async: false,\r\n");
      out.write("\t\t\t\t//             type : 'POST',\r\n");
      out.write("\t\t\t\t//             data : {userno: userno},\r\n");
      out.write("\t\t\t\t//             url : \"/Sector/jumincheck\",\r\n");
      out.write("\t\t\t\t//             // dataType : \"json\", \r\n");
      out.write("\t\t\t\t//             // contentType: \"application/json; charset=UTF-8\",\r\n");
      out.write("\t\t\t\t//             success : function(data) {\r\n");
      out.write("\t\t\t\t//                 if (data > 0) {\r\n");
      out.write("\t\t\t\t//                     alert(\"이미 가입된 주민등록번호 입니다.\");\r\n");
      out.write("\t\t\t\t//                     $(\"#usernumber1\").focus();\r\n");
      out.write("\t\t\t\t//                     $(\"#usernumber2\").val(\"\");\r\n");
      out.write("\t\t\t\t// \t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t//                 }\r\n");
      out.write("\t\t\t\t// \t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t// \t\t\t\t}\r\n");
      out.write("\t\t\t\t//             },\r\n");
      out.write("\t\t\t\t//             error : function(error) {\r\n");
      out.write("\t\t\t\t//                 alert(\"error : \" + error);\r\n");
      out.write("\t\t\t\t//             }\r\n");
      out.write("\t\t\t\t// \t\t});\r\n");
      out.write("\t\t\t\t// \t\tdocument.getElementById(\"usernumber1\").style.borderBottom=\"solid 2px #489CFF\";\r\n");
      out.write("\t\t\t\t// \t\tdocument.getElementById(\"usernumber2\").style.borderBottom=\"solid 2px #489CFF\";\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t// }\t\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t  function idcheck(){\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\tfunction passCheck(){\r\n");
      out.write("\t\t\t\t\t\tif ($(\"#userid\").val()==($(\"#userpwd\").val()) && $(\"#userpwd\").val() != \"\") {\r\n");
      out.write("\t\t\t\t\t  alert(\"아이디와 비밀번호를 갖게 만들 수 없습니다.\");\r\n");
      out.write("\t\t\t\t\t  $(\"#userpwd\").val(\"\");\r\n");
      out.write("\t\t\t\t\t  $(\"#userpwd\").focus();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  return false;\r\n");
      out.write("\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif(!getPwd.test($(\"#userpwd\").val()) && $(\"#userpwd\").val() != \"\") {\r\n");
      out.write("\t\t\t\t\t  alert(\"비밀번호 형식에 맞게 작성해주세요. (소문자 6~12자 이내 및 숫자 포함)\");\r\n");
      out.write("\t\t\t\t\t  $(\"#userpwd\").val(\"\");\r\n");
      out.write("\t\t\t\t\t  $(\"#userpwd\").focus();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t  return false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif($(\"#userpwd\").val() == \"\"){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\tfunction passCheck2(){\r\n");
      out.write("\t\t\t\t\t\tif($(\"#userpwd\").val() != ($(\"#userpwd2\").val()) && $(\"#userpwd2\").val() != \"\"){ \r\n");
      out.write("\t\t\t\t\t  alert(\"비밀번호가 서로 일치하지 않습니다.\");\r\n");
      out.write("\t\t\t\t\t  $(\"#userpwd2\").val(\"\");\r\n");
      out.write("\t\t\t\t\t  $(\"#userpwd2\").focus();\r\n");
      out.write("\t\t\t\t\t  return false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif($(\"#userpwd2\").val() == \"\"){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\tfunction nameCheck(){\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\tvar getName= RegExp(/^[가-힣]{2,}$/);\r\n");
      out.write("\t\t\t\t\t\tif (!getName.test($(\"#username\").val()) && $(\"#username\").val() != \"\") {\r\n");
      out.write("\t\t\t\t\t\t\talert(\"이름을 올바르게 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#username\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#username\").focus();\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif($(\"#username\").val() == \"\"){\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\tfunction idCheck2(){\r\n");
      out.write("\t\t\t\t\t\tvar getCheck= RegExp(/^[a-zA-Z0-9]{4,12}$/);\r\n");
      out.write("\t\t\t\t\t\tvar userid =  $(\"#userid\").val();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t  if(!getCheck.test($(\"#userid\").val()) && $(\"#userid\").val() != \"\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"아이디 형식에 맞게 작성해주세요. (숫자 및 소문자 4~12자 이내)\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#userid\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#userid\").focus();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t  if($(\"#userid\").val() == \"\"){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\tfunction phoneCheck(){\r\n");
      out.write("\t\t\t\t\t\tvar getPhone= RegExp(/^010\\d{4}\\d{4}$/);\r\n");
      out.write("\t\t\t\t\t\tvar phone =  $(\"#phone\").val();\r\n");
      out.write("\t\t\t\t\t\t// alert(userid);\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t  if(!getPhone.test($(\"#phone\").val()) && $(\"#phone\").val() != \"\"){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"전화번호 형식에 맞게 작성해주세요. (ex : 01012345678)\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#phone\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#phone\").focus();\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t  }\r\n");
      out.write("\t\t\t\t\t\t  if($(\"#phone\").val() == \"\"){\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<!-- 중복체크 검사 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("    </head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- Header -->\r\n");
      out.write("\t\t<header id=\"header\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<!-- Logo -->\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-brand\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"logo\" href=\"index.do\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/danim/resources/img/logo.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /Logo -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Mobile toggle -->\r\n");
      out.write("\t\t\t\t\t<button class=\"navbar-toggle\">\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<!-- /Mobile toggle -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Navigation -->\r\n");
      out.write("\t\t\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"main-menu nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.do\">메인으로</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"loginForm.do\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"enrollForm.do\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"contactForm.do\">문의하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"noticeForm.do?page=1\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<!-- /Navigation -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<!-- /Header -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Hero-area -->\r\n");
      out.write("\t\t<div class=\"hero-area section\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Backgound Image -->\r\n");
      out.write("\t\t\t<div class=\"bg-image bg-parallax overlay\" style=\"background-image:url(/danim/resources/img/page-background.jpg)\"></div>\r\n");
      out.write("\t\t\t<!-- /Backgound Image -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-10 col-md-offset-1 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"hero-area-tree\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"index.do\">Danim:</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"white-text\">회원가입</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /Hero-area -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Contact -->\r\n");
      out.write("\t\t<div id=\"contact\" class=\"section\" >\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- container -->\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- enroll form -->\r\n");
      out.write("\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t<form action=\"\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contact-form\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>개인정보</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input\" type=\"email\" name=\"userid\" id=\"userid\" placeholder=\"아이디로 사용할 이메일\"style=\"width: 70%;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"main-button icon-button pull-right emailchkbtn\" >인증 메일 발송</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input\" type=\"text\" name=\"emailcheck\" id=\"emailchkinput\" placeholder=\"인증 번호\" style=\"width: 75%;\" hidden>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"main-button icon-button pull-right complete hidden\">인증 완료</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input\" type=\"text\" name=\"nickname\" id=\"nickname\" placeholder=\"닉네임\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input\" type=\"text\" name=\"username\"id=\"username\" placeholder=\"이름\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input\" type=\"text\" name=\"usernum\" id=\"usernumber\" placeholder=\"주민등록번호 ('-' 생략)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input\" type=\"password\" name=\"userpwd\" id=\"userpwd\" placeholder=\"비밀번호\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input\" type=\"password\" name=\"userpwd2\" id=\"userpwd2\" placeholder=\"비밀번호 확인\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input\" type=\"text\" name=\"phone\" id=\"phone\" placeholder=\"전화번호 ('-' 생략)\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select name=\"accountname\" id=\"accountname\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"우리\">우리은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"기업\">IBK기업은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"하나\">KEB하나은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"국민\">국민은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"신한\">신한은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"농협\">농협은행</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"신협\">신협</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input acname\" type=\"text\" name=\"account\" id=\"account\" placeholder=\"계좌번호 ('-' 생략)\" style=\"width: 79%;\"> <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>활동 지역</h4>\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input chk\" type=\"checkbox\" name=\"ground\" id=\"seoul\" value=\"서울\"> 서울 &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input chk\" type=\"checkbox\" name=\"\" id=\"gyunggi\" value=\"경기\"> 경기 &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input chk\" type=\"checkbox\" name=\"\" id=\"gangwon\" value=\"강원\"> 강원 &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input chk\" type=\"checkbox\" name=\"ground\" id=\"choongbook\" value=\"충북\"> 충북 &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input chk\" type=\"checkbox\" name=\"ground\" id=\"choongnam\" value=\"충남\"> 충남 &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input chk\" type=\"checkbox\" name=\"jeonbook\" id=\"jeonbook\" value=\"전북\"> 전북 &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input chk\" type=\"checkbox\" name=\"jeonnam\" id=\"jeonnam\" value=\"전남\"> 전남 &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input chk\" type=\"checkbox\" name=\"gyungbook\" id=\"gyungbook\" value=\"경북\"> 경북 &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input chk\" type=\"checkbox\" name=\"gyungnam\" id=\"gyungnam\" value=\"경남\"> 경남 &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input chk\" type=\"checkbox\" name=\"jeju\" id=\"jeju\" value=\"제주\"> 제주\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /enroll form -->\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t$(function(){\r\n");
      out.write("\t\t\t\t\t\t$('.emailchkbtn').click(function(){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar userid = $('#userid').val();\r\n");
      out.write("\t\t\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\t\t\t\t\tdata : { userid : userid },\r\n");
      out.write("\t\t\t\t\t\t\t\turl : \"/danim/emailcheck\",\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\tsuccess : function(data){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tswitch(data){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcase \"100\": alert(\"인증 메일이 전송되었습니다.\"); \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$('#emailchkinput').attr('hidden',false).focus();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$('.complete').removeClass(\"hidden\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$('.emailchkbtn').addClass(\"hidden\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t$('#userid').attr(\"disabled\",true);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdocument.getElementById('userid').style.width=\"100%\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcase \"200\": alert(\"이미 사용중인 이메일입니다.\"); $('#userid').focus(); break;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcase \"900\": alert(\"알 수 없는 에러 발생\"); $('#userid').focus(); break;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\terror : function(error){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(error); \r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t// window.open(\"./enroll_emailcheck.jsp\",\"PopupWin\",\"width=500, height=300\");\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t// $('.emailchkbtn').val('재발송');\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- simple sign up -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5 col-md-offset-1\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"contact-form\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>'다님' 이용약관 동의</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea class=\"input policy\" name=\"policy1\" style=\"height: 106px;\" >\r\n");
      out.write("다양한 다님 서비스를 즐겨보세요.\r\n");
      out.write("다님은 www.danim.com을 비롯한 다님 도메인의 웹사이트 및 응용프로그램(어플리케이션, 앱)을 통해 정보 검색, 다른 이용자와의 커뮤니케이션, 콘텐츠 제공, 상품 쇼핑 등 여러분의 생활에 편리함을 더할 수 있는 다양한 서비스를 제공하고 있습니다.\r\n");
      out.write("여러분은 PC, 휴대폰 등 인터넷 이용이 가능한 각종 단말기를 통해 각양각색의 다님 서비스를 자유롭게 이용하실 수 있으며, 개별 서비스들의 구체적인 내용은 각 서비스 상의 안내, 공지사항, 다님 웹고객센터(이하 ‘고객센터’) 도움말 등에서 쉽게 확인하실 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("다님은 기본적으로 여러분 모두에게 동일한 내용의 서비스를 제공합니다. 다만, '청소년보호법' 등 관련 법령이나 기타 개별 서비스 제공에서의 특별한 필요에 의해서 연령 또는 일정한 등급을 기준으로 이용자를 구분하여 제공하는 서비스의 내용, 이용 시간, 이용 횟수 등을 다르게 하는 등 일부 이용을 제한하는 경우가 있습니다. 자세한 내용은 역시 각 서비스 상의 안내, 공지사항, 고객센터 도움말 등에서 확인하실 수 있습니다.\r\n");
      out.write("\r\n");
      out.write("다님 서비스에는 기본적으로 본 약관이 적용됩니다만 다님가 다양한 서비스를 제공하는 과정에서 부득이 본 약관 외 별도의 약관, 운영정책 등을 적용하는 경우(예, 다님페이, V LIVE 등)가 있습니다. 그리고 다님 계열사가 제공하는 특정 서비스의 경우에도(예, LINE, SNOW등) 해당 운영 회사가 정한 고유의 약관, 운영정책 등이 적용될 수 있습니다. 이러한 내용은 각각의 해당 서비스 초기 화면에서 확인해 주시기 바랍니다.\r\n");
      out.write("\r\n");
      out.write("회원으로 가입하시면 다님 서비스를 보다 편리하게 이용할 수 있습니다.\r\n");
      out.write("여러분은 본 약관을 읽고 동의하신 후 회원 가입을 신청하실 수 있으며, 다님은 이에 대한 승낙을 통해 회원 가입 절차를 완료하고 여러분께 다님 서비스 이용 계정(이하 ‘계정’)을 부여합니다. 계정이란 회원이 다님 서비스에 로그인한 이후 이용하는 각종 서비스 이용 이력을 회원 별로 관리하기 위해 설정한 회원 식별 단위를 말합니다. 회원은 자신의 계정을 통해 좀더 다양한 다님 서비스를 보다 편리하게 이용할 수 있습니다. 이와 관련한 상세한 내용은 계정 운영정책 및 고객센터 내 다님 회원가입 방법 등에서 확인해 주세요.\r\n");
      out.write("\r\n");
      out.write("다님은 단체에 속한 여러 구성원들이 공동의 계정으로 다님 서비스를 함께 이용할 수 있도록 단체회원 계정도 부여하고 있습니다. 단체회원 구성원들은 하나의 계정 및 아이디(ID)를 공유하되 각자 개별적으로 설정한 비밀번호를 입력하여 계정에 로그인하고 각종 서비스를 이용하게 됩니다. 단체회원은 관리자와 멤버로 구성되며, 관리자는 구성원 전부로부터 권한을 위임 받아 단체회원을 대표하고 단체회원 계정을 운용합니다.\r\n");
      out.write("따라서 관리자는 단체회원 계정을 통해 별도 약관 또는 기존 약관 개정에 대해 동의하거나 단체회원에서 탈퇴할 수 있고, 멤버들의 단체회원 계정 로그인 방법 및 이를 통한 게시물 게재 등 다님 서비스 이용을 관리(게시물 삭제 포함)할 수 있습니다. 본 약관에서 규정한 사항은 원칙적으로 구성원 모두에게 적용되며, 각각의 구성원은 다른 구성원들의 단체회원 계정 및 아이디(ID)를 통한 서비스 이용에 관해 연대책임을 부담합니다.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>개인정보 수집 및 이용에 대한 안내</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea class=\"input policy\" name=\"policy2\" style=\"height: 106px;\">\r\n");
      out.write("1. 개인정보의 처리 목적 (‘www.danim.com’이하 ‘Danim’) 은(는) 다음의 목적을 위하여 개인정보를 처리하고 있으며, 다음의 목적 이외의 용도로는 이용하지 않습니다.\r\n");
      out.write("- 고객 가입의사 확인, 고객에 대한 서비스 제공에 따른 본인 식별.인증, 회원자격 유지.관리, 물품 또는 서비스 공급에 따른 금액 결제, 물품 또는 서비스의 공급.배송 등\r\n");
      out.write("2. 개인정보의 처리 및 보유 기간\r\n");
      out.write("① (‘www.danim.com’이하 ‘Danim’) 은(는) 정보주체로부터 개인정보를 수집할 때 동의 받은 개인정보 보유․이용기간 또는 법령에 따른 개인정보 보유․이용기간 내에서 개인정보를 처리․보유합니다.\r\n");
      out.write("② 구체적인 개인정보 처리 및 보유 기간은 다음과 같습니다.\r\n");
      out.write("☞ 아래 예시를 참고하여 개인정보 처리업무와 개인정보 처리업무에 대한 보유기간 및 관련 법령, 근거 등을 기재합니다.\r\n");
      out.write("(예시)- 고객 가입 및 관리 : 서비스 이용계약 또는 회원가입 해지시까지, 다만 채권․채무관계 잔존시에는 해당 채권․채무관계 정산시까지\r\n");
      out.write("- 전자상거래에서의 계약․청약철회, 대금결제, 재화 등 공급기록 : 5년 \r\n");
      out.write("3. 개인정보의 제3자 제공에 관한 사항\r\n");
      out.write("① ('www.danim.com'이하 'Danim')은(는) 정보주체의 동의, 법률의 특별한 규정 등 개인정보 보호법 제17조 및 제18조에 해당하는 경우에만 개인정보를 제3자에게 제공합니다.\r\n");
      out.write("② ('www.danim.com')은(는) 다음과 같이 개인정보를 제3자에게 제공하고 있습니다.\r\n");
      out.write("1. <>\r\n");
      out.write("- 개인정보를 제공받는 자 : \r\n");
      out.write("- 제공받는 자의 개인정보 이용목적 : \r\n");
      out.write("- 제공받는 자의 보유.이용기간:\r\n");
      out.write("4. 개인정보처리 위탁\r\n");
      out.write("① ('Danim')은(는) 원활한 개인정보 업무처리를 위하여 다음과 같이 개인정보 처리업무를 위탁하고 있습니다.\r\n");
      out.write("1. <>\r\n");
      out.write("- 위탁받는 자 (수탁자) : \r\n");
      out.write("- 위탁하는 업무의 내용 : \r\n");
      out.write("- 위탁기간 :\r\n");
      out.write("② ('www.danim.com'이하 'Danim')은(는) 위탁계약 체결시 개인정보 보호법 제25조에 따라 위탁업무 수행목적 외 개인정보 처리금지, 기술적․관리적 보호조치, 재위탁 제한, 수탁자에 대한 관리․감독, 손해배상 등 책임에 관한 사항을 계약서 등 문서에 명시하고, 수탁자가 개인정보를 안전하게 처리하는지를 감독하고 있습니다.\r\n");
      out.write("③ 위탁업무의 내용이나 수탁자가 변경될 경우에는 지체없이 본 개인정보 처리방침을 통하여 공개하도록 하겠습니다.\r\n");
      out.write("5. 정보주체와 법정대리인의 권리·의무 및 그 행사방법 이용자는 개인정보주체로써 다음과 같은 권리를 행사할 수 있습니다.\r\n");
      out.write("① 정보주체는 Danim 그룹웨어(‘www.danim.com’이하 ‘Danim) 에 대해 언제든지 다음 각 호의 개인정보 보호 관련 권리를 행사할 수 있습니다.\r\n");
      out.write("1. 개인정보 열람요구\r\n");
      out.write("2. 오류 등이 있을 경우 정정 요구\r\n");
      out.write("3. 삭제요구\r\n");
      out.write("4. 처리정지 요구\r\n");
      out.write("6. 처리하는 개인정보의 항목 작성 \r\n");
      out.write("① ('www.danim.com'이하 'Danim')은(는) 다음의 개인정보 항목을 처리하고 있습니다.\r\n");
      out.write("1<회원 관리 및 서비스 제공>\r\n");
      out.write("▶ 개인정보 보호책임자 \r\n");
      out.write("성명 :구건모\r\n");
      out.write("직책 :대표\r\n");
      out.write("직급 :대표\r\n");
      out.write("연락처 :01025653871, gunmo9511@gmail.com, \r\n");
      out.write("※ 개인정보 보호 담당부서로 연결됩니다.\r\n");
      out.write("▶ 개인정보 보호 담당부서\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4>위치정보 이용약관 동의</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea class=\"input policy\" name=\"policy3\" style=\"height: 107px;\">\r\n");
      out.write("위치정보 이용약관에 동의하시면, 위치를 활용한 광고 정보 수신 등을 포함하는 다님 위치기반 서비스를 이용할 수 있습니다.\r\n");
      out.write("제 1 조 (목적)\r\n");
      out.write("이 약관은 다님 주식회사 (이하 “회사”)가 제공하는 위치정보사업 또는 위치기반서비스사업과 관련하여 회사와 개인위치정보주체와의 권리, 의무 및 책임사항, 기타 필요한 사항을 규정함을 목적으로 합니다.\r\n");
      out.write("\r\n");
      out.write("제 2 조 (약관 외 준칙)\r\n");
      out.write("이 약관에 명시되지 않은 사항은 위치정보의 보호 및 이용 등에 관한 법률, 정보통신망 이용촉진 및 정보보호 등에 관한 법률, 전기통신기본법, 전기통신사업법 등 관계법령과 회사의 이용약관 및 개인정보처리방침, 회사가 별도로 정한 지침 등에 의합니다.\r\n");
      out.write("\r\n");
      out.write("제 3 조 (서비스 내용 및 요금)\r\n");
      out.write("①회사는 직접 위치정보를 수집하거나 위치정보사업자인 이동통신사로부터 위치정보를 전달받아 아래와 같은 위치기반서비스를 제공합니다.\r\n");
      out.write("1.Geo Tagging 서비스: 게시물에 포함된 개인위치정보주체 또는 이동성 있는 기기의 위치정보가 게시물과 함께 저장됩니다.\r\n");
      out.write("2.위치정보를 활용한 검색결과 제공 서비스: 정보 검색을 요청하거나 개인위치정보주체 또는 이동성 있는 기기의 위치정보를 제공 시 본 위치정보를 이용한 검색결과 및 주변결과(맛집, 주변업체, 교통수단 등)를 제시합니다.\r\n");
      out.write("3.위치정보를 활용한 친구찾기 및 친구맺기: 현재 위치를 활용하여 친구를 찾아주거나 친구를 추천하여 줍니다.\r\n");
      out.write("4.연락처 교환하기: 위치정보를 활용하여 친구와 연락처를 교환할 수 있습니다.\r\n");
      out.write("5.이용자 위치를 활용한 광고정보 제공: 검색결과 또는 기타 서비스 이용 과정에서 개인위치정보주체 또는 이동성 있는 기기의 위치를 이용하여 광고소재를 제시합니다.\r\n");
      out.write("6. 이용자 보호 및 부정 이용 방지: 개인위치정보주체 또는 이동성 있는 기기의 위치를 이용하여 권한없는 자의 비정상적인 서비스 이용 시도 등을 차단합니다.\r\n");
      out.write("7. 위치정보 공유: 개인위치정보주체 또는 이동성 있는 기기의 위치정보를 안심귀가 등을 목적으로 지인 또는 개인위치정보주체가 지정한 제3자에게 공유합니다.\r\n");
      out.write("8. 길 안내 등 생활편의 서비스 제공: 교통정보와 길 안내 등 최적의 경로를 지도로 제공하며, 주변 시설물 찾기, 뉴스/날씨 등 생활정보, 긴급구조 서비스 등 다양한 운전 및 생활 편의 서비스를 제공합니다.\r\n");
      out.write("②제1항 위치기반서비스의 이용요금은 무료입니다.\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input agree\" type=\"checkbox\" id=\"agree\">&nbsp;위의 모든 약관에 동의합니다. <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"main-button icon-button pull-right enrollbutton\">가입하기</button>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t<!-- simple sign up -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /container -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /Contact -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t<footer id=\"footer\" class=\"section\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- container -->\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- footer logo -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-logo\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"logo\" href=\"index.do\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/danim/resources/img/logo.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t<div id=\"bottom-footer\" class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- social -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 col-md-push-8\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"footer-social\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"instagram\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"github\"><i class=\"fa fa-github\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /social -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- copyright -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-md-pull-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-copyright\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>&copy; Copyright Koo gun mo. | This Poroject is made with Kim nam gyu & You young joon</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /copyright -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /container -->\r\n");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t<!-- /Footer -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- preloader -->\r\n");
      out.write("\t\t<div id='preloader'><div class='preloader'></div></div>\r\n");
      out.write("\t\t<!-- /preloader -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- jQuery Plugins -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/danim/resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/danim/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/danim/resources/js/google-map.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/danim/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
