/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2019-10-23 04:02:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\t <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->\r\n");
      out.write("\r\n");
      out.write("\t\t<title>다님: 로그인</title>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Google font -->\r\n");
      out.write("\t\t<link href=\"https://fonts.googleapis.com/css?family=Lato:700%7CMontserrat:400,600\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Bootstrap -->\r\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"/danim/resources/css/bootstrap.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Font Awesome Icon -->\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/danim/resources/css/font-awesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Custom stlylesheet -->\r\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"/danim/resources/css/style.css\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-1.12.4.min.js\" ></script>\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tfunction logincheck(){\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("    </head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Header -->\r\n");
      out.write("\t\t<header id=\"header\">\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t\t<!-- Logo -->\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-brand\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"logo\" href=\"index.do\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"/danim/resources/img/logo.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /Logo -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- Mobile toggle -->\r\n");
      out.write("\t\t\t\t\t<button class=\"navbar-toggle\">\r\n");
      out.write("\t\t\t\t\t\t<span></span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t<!-- /Mobile toggle -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- Navigation -->\r\n");
      out.write("\t\t\t\t<nav id=\"nav\">\r\n");
      out.write("\t\t\t\t\t<ul class=\"main-menu nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"index.do\">메인으로</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"loginForm.do\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"enrollForm.do\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"contactForm.do\">문의하기</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"noticeForm.do?page=1\">공지사항</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</nav>\r\n");
      out.write("\t\t\t\t<!-- /Navigation -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t<!-- /Header -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Hero-area -->\r\n");
      out.write("\t\t<div class=\"hero-area section\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- Backgound Image -->\r\n");
      out.write("\t\t\t<div class=\"bg-image bg-parallax overlay\" style=\"background-image:url(/danim/resources/img/page-background.jpg)\"></div>\r\n");
      out.write("\t\t\t<!-- /Backgound Image -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-10 col-md-offset-1 text-center\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"hero-area-tree\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\">Danim:</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t<h1 class=\"white-text\">로그인</h1>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /Hero-area -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Contact -->\r\n");
      out.write("\t\t<div id=\"contact\" class=\"section\" >\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- container -->\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- login form -->\r\n");
      out.write("\t\t\t\t\t<br><br>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5 col-md-offset-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"contact-form\">\r\n");
      out.write("\t\t\t\t\t\t\t<h4>Login</h4>\r\n");
      out.write("\t\t\t\t\t\t\t<form action=\"login.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input login\" type=\"text\" name=\"userid\" placeholder=\"아이디\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"input login\" type=\"password\" name=\"userpwd\" placeholder=\"비밀번호\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"main-button icon-button pull-right loginbutton\">로그인</button>\r\n");
      out.write("\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-center login-a\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"logintext la\">아이디 또는 비밀번호를 잊으셨나요? <a href=\"#\" class=\"login\">계정찾기</a></a><br>\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"logintext la\">아직 회원이 아니신가요? <a href=\"enrollForm.do\" class=\"login\">회원가입</a></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /container -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- /Contact -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Footer -->\r\n");
      out.write("\t\t<footer id=\"footer\" class=\"section\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- container -->\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- footer logo -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-logo\">\r\n");
      out.write("\t\t\t\t\t\t\t<a class=\"logo\" href=\"index.do\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"/danim/resources/img/logo.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- /row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- row -->\r\n");
      out.write("\t\t\t\t<div id=\"bottom-footer\" class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- social -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-4 col-md-push-8\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"footer-social\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"instagram\"><i class=\"fa fa-instagram\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\" class=\"github\"><i class=\"fa fa-github\"></i></a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /social -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- copyright -->\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-8 col-md-pull-4\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"footer-copyright\">\r\n");
      out.write("\t\t\t\t\t\t\t<span>&copy; Copyright Koo gun mo. | This Poroject is made with Kim nam gyu & You young joon</a></span>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<!-- /copyright -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<!-- row -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- /container -->\r\n");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t<!-- /Footer -->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- preloader -->\r\n");
      out.write("\t\t<div id='preloader'><div class='preloader'></div></div>\r\n");
      out.write("\t\t<!-- /preloader -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- jQuery Plugins -->\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/danim/resources/js/jquery.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/danim/resources/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=true\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/danim/resources/js/google-map.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/danim/resources/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
